FROM {docker_base}

USER root

RUN pacman --noconfirm -Syyu && \
    pacman --noconfirm -S base-devel sudo {dependencies} && \
    echo "%wheel ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    {useradd}
    mkdir -p /distropackager && \
    chown -R {user}:wheel /distropackager

USER {user}
